name: CICD PIPELINE

on:
  push:

jobs:
  build:
    name: build_stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: CML
        uses: iterative/setup-cml@v2

      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Running main file
        run: |
          python main.py
      
      
      - name: Unit Tests
        run: |
          python -m unittest discover

      - name: Creating CML Report 
        env:
          REPO_TOKEN: ${{secrets.MY_TOKEN}}
        run: |
          echo "Report" >> Report.md
          echo "Bar Plot" >> Report.md
          echo '![](./bars.png "Bar Plot")' >> Report.md

          cml comment create Report.md
          

    
  