name: CI_PIPELINE

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade python
          pip install -r requirements.txt

      - name: Unit Tests
        run: |
          python -m unittest discover

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      jobs:
        name: Deployingcode
        runs: |
